* 存储类型：auot static register extern（说明型）
auto：默认，自动分配空间，自动回收空间
register：（建议型）寄存器类型，只能定义局部变量，不能定义全局变量；大小有限制，只能定义32位大小的数据类型，
           如double类型，就不可以；寄存器类型没有地址，所以一个寄存器类型的变量无法打印出地址查看或使用。
static：静态类型，自动初始化为0或空值，并且其变量的值有继承性;另外，常用于修饰函数或变量。
extern：说明型，意味着不能改变被说明的变量的值或类型
值：匹配
* 变量的生命周期和作用范围
1）全局变量和局部变量
2）局部变量和局部变量
The primary purpose of variables is to store data in memory for later use.
Each variable in C has specific type, which determines the size and layout
of the variable's memory, the range of values that can be stored within
that memory, and the set of operaations that can be applied to the variable.
* Rules for declaring Variables:
1. A variable can contain alphabets, digits, and underscore.
2. The use of whitespace is not allowed within the variable name.
3. We cannot use any reserved word or keyword as a variable name.
   e.g. int, float, etc.
4. Variable can't start with a digit. Only Alphabet & underscore can be used.
* Declaring New Variable in C Language:
  A declaration statement tells the compiler to create a new variable.
  It also specifies the data type and memory required for the variable.
* Initializing Variables in C language
  A initialization statement tells compiler to assign a value to variable.
  The assigned value must be compatiable with the data type of the variable.
* Types of Variables in C Language
** 1. Local Variable
   A Variable that is declared inside the function or a block is called local variable.
   Local Variable must be declared at the start of the block.

** 2. Static Variable
** 3. Automatic Variable
** 4. Global Variable
** External Variable
